apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: k8s-webhook
  name: k8s-webhook-rc
spec:
  replicas: 1
  selector:
    name: k8s-webhook
  template:
    metadata:
      labels:
        name: k8s-webhook
    spec:
      containers:
      - image: kaija/scale_webhook:v1.1
        name: k8s-webhook
        env:
        - name: PORT
          value: '80'
        - name: KUBERNETES_API_TOKEN
          value: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        ports:
        - containerPort: 80
          name: webhook-port
          protocol: TCP
